### ISSUE TITLE
[後台] 管理員可管理產品可用顏色

### ISSUE THREAD

**Issue by passerbyid** [GlobalMDS/Front-End#7]
# 功能概述
管理員可於系統後台管理產品會用到的顏色。
因實體產品顏色以 Pantone 作為色碼標準，顏色管理會包含顏色的 Pantone Code、顏色名稱（多語言）。產品顏色於顯示時，會以和該 PantoneCode 最似的 RGB 顏色來顯示，讓使用者作為參考。

# todo
- [ ] 顏色管理頁面。
- [ ] 顯示現有顏色（pantone_code、title）。
- [ ] 增加某顏色（pantone_code、title）。
- [ ] 編輯某顏色（pantone_code、title）。
- [ ] 刪除某顏色。
- [ ] 尋找合適的 PantoneCode-RGB 轉換表。
- [ ] 於顯示顏色時，顯示其最似的 RGB 顏色。
